context:
  version: "2.18.1"

package:
  name: fsdgenfsd
  version: ${{ version }}

source:
  url: https://github.com/FacilityApi/Facility/archive/nuget.${{ version }}.tar.gz
  sha256: 500e491317c1e16136a264f08d2520fa81c651dc1ef845303790e7d2ec2b397e

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - fsdgenfsd --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Tools and libraries for working with the Facility API Framework.
  homepage: https://github.com/FaciltyApi/Facility
  repository: https://github.com/FaciltyApi/Facility

extra:
  recipe-maintainers:
    - danielnachun
