context:
  version: "2.19.0"

package:
  name: fsdgenfsd
  version: ${{ version }}

source:
  url: https://github.com/FacilityApi/Facility/archive/nuget.${{ version }}.tar.gz
  sha256: e7fec2fe39255368b9c38419c75feefbb4a7af3640b13fe16b4e3d4ccfdc20bd

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - fsdgenfsd --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Tools and libraries for working with the Facility API Framework.
  homepage: https://github.com/FaciltyApi/Facility
  repository: https://github.com/FaciltyApi/Facility

extra:
  recipe-maintainers:
    - danielnachun
