context:
  version: "2.18.0"

package:
  name: fsdgenfsd
  version: ${{ version }}

source:
  url: https://github.com/FacilityApi/Facility/archive/nuget.${{ version }}.tar.gz
  sha256: 59194c747c6f7f2aaaac02e6933266c8fbab7b549a063701e501d489d7883593

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - fsdgenfsd --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Tools and libraries for working with the Facility API Framework.
  homepage: https://github.com/FaciltyApi/Facility
  repository: https://github.com/FaciltyApi/Facility

extra:
  recipe-maintainers:
    - danielnachun
